# Challenge

Now that you've learned about random forests and decision trees let's do an exercise in accuracy. You know that random forests are basically a collection of decision trees. But how do the accuracies of the two models compare?

So here's what you should do. Pick a dataset. It could be one you've worked with before or it could be a new one. Then build the best decision tree you can.

Now try to match that with the simplest random forest you can. For our purposes measure simplicity with [runtime](https://stackoverflow.com/questions/1557571/how-do-i-get-time-of-a-python-programs-execution). Compare that to the runtime of the decision tree. This is imperfect but just go with it.

Hopefully out of this you'll see the power of random forests, but also their potential costs. Remember, in the real world you won't necessarily be dealing with thousands of rows. It could be millions, billions, or even more.

### Import Statements

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy
from sklearn import ensemble
from sklearn.model_selection import cross_val_score
import matplotlib.pyplot as plt
%matplotlib inline

# This is the model we'll be using.
from sklearn import tree

# A convenience for displaying visualizations.
from IPython.display import Image

# Packages for rendering our tree.
import pydotplus
import graphviz

ModuleNotFoundError: No module named 'graphviz'

### The Dataframe

In [4]:
lending_df = pd.read_csv('LoanStats3d.csv', nrows=5000, skipinitialspace=True, header=1)

### Data Cleaning

In [5]:
categorical = lending_df.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

term
2
int_rate
42
grade
7
sub_grade
35
emp_title
3113
emp_length
11
home_ownership
3
verification_status
3
issue_d
1
loan_status
7
pymnt_plan
1
url
5000
desc
1
purpose
12
title
12
zip_code
708
addr_state
49
earliest_cr_line
453
revol_util
981
initial_list_status
2
last_pymnt_d
13
next_pymnt_d
2
last_credit_pull_d
14
application_type
2
verification_status_joint
3

Drop the columns that have 30+ unique values.

In [6]:
# Convert ID and Interest Rate to numeric.
lending_df['id'] = pd.to_numeric(lending_df['id'], errors='coerce')
lending_df['int_rate'] = pd.to_numeric(lending_df['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
lending_df.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [7]:
# This will convert categorical variables into dummy/indicator variables.
pd.get_dummies(lending_df)

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,int_rate,installment,annual_inc,dti,delinq_2yrs,...,last_credit_pull_d_Mar-16,last_credit_pull_d_May-16,last_credit_pull_d_Nov-16,last_credit_pull_d_Oct-16,last_credit_pull_d_Sep-16,application_type_INDIVIDUAL,application_type_JOINT,verification_status_joint_Not Verified,verification_status_joint_Source Verified,verification_status_joint_Verified
0,68009401,72868139,16000,16000,16000,14.85,379.39,48000.0,33.18,0,...,0,0,0,0,0,1,0,0,0,0
1,68354783,73244544,9600,9600,9600,7.49,298.58,60000.0,22.44,0,...,0,0,0,0,0,1,0,0,0,0
2,68466916,73356753,25000,25000,25000,7.49,777.55,109000.0,26.02,0,...,0,0,0,0,0,1,0,0,0,0
3,68466961,73356799,28000,28000,28000,6.49,858.05,92000.0,21.60,0,...,0,0,0,0,0,1,0,0,0,0
4,68495092,73384866,8650,8650,8650,19.89,320.99,55000.0,25.49,0,...,0,0,0,0,0,1,0,0,0,0
5,68506798,73396623,23000,23000,23000,8.49,471.77,64000.0,18.28,0,...,0,0,0,0,0,1,0,0,0,0
6,68566886,73456723,29900,29900,29900,12.88,678.49,65000.0,21.77,0,...,0,0,0,0,0,1,0,0,0,0
7,68577849,73467703,18000,18000,18000,11.99,400.31,112000.0,8.68,0,...,0,0,0,0,0,1,0,0,0,0
8,66310712,71035433,35000,35000,35000,14.85,829.90,110000.0,17.06,0,...,0,0,0,0,0,1,0,0,0,0
9,68476807,73366655,10400,10400,10400,22.45,289.91,104433.0,25.37,1,...,0,0,0,0,0,1,0,0,0,0
10,68341763,72928789,20000,20000,20000,10.78,432.66,63000.0,10.78,0,...,0,0,0,0,0,0,1,1,0,0
11,68356421,73246236,22400,22400,22400,12.88,508.30,95000.0,22.98,0,...,0,0,0,0,0,1,0,0,0,0
12,68426545,73316365,16000,16000,16000,12.88,363.07,70000.0,26.40,0,...,0,0,0,0,0,1,0,0,0,0
13,68407277,73297111,3600,3600,3600,13.99,123.03,55000.0,5.91,0,...,0,0,0,0,0,1,0,0,0,0
14,68355089,73244858,24700,24700,24700,11.99,820.28,65000.0,16.06,1,...,0,1,0,0,0,1,0,0,0,0
15,68466926,73356763,10000,10000,10000,6.49,306.45,85000.0,13.07,0,...,0,0,0,0,0,1,0,0,0,0
16,68338832,73542831,1400,1400,1400,12.88,47.10,64000.0,34.95,0,...,0,0,0,0,0,1,0,0,0,0
17,68426831,73316657,11950,11950,11950,13.44,405.18,34000.0,10.20,0,...,0,0,0,0,0,1,0,0,0,0
18,66624733,71350547,18000,18000,18000,19.48,471.70,150000.0,9.39,0,...,0,0,0,0,0,1,0,0,0,0
19,68616873,73519699,8000,8000,8000,11.48,263.74,42000.0,34.80,0,...,0,0,0,0,0,1,0,0,0,0
20,67275481,72077199,20000,20000,20000,8.49,631.26,85000.0,17.61,1,...,0,0,0,0,0,1,0,0,0,0
21,68476668,73366513,20000,20000,20000,9.17,637.58,180000.0,14.67,0,...,0,0,1,0,0,1,0,0,0,0
22,68476702,73366548,28000,28000,28000,13.44,949.38,125000.0,7.49,0,...,0,0,0,0,0,1,0,0,0,0
23,68436666,73326493,5000,5000,5000,13.44,169.54,79000.0,12.70,0,...,0,0,0,0,0,1,0,0,0,0
24,68596180,73485987,20000,20000,20000,5.32,602.30,65000.0,18.83,0,...,0,0,0,0,0,1,0,0,0,0
25,67849662,72708407,4225,4225,4225,14.85,146.16,35000.0,15.22,2,...,0,0,0,0,0,1,0,0,0,0
26,68526883,73416719,15000,15000,15000,5.32,451.73,44000.0,15.34,0,...,0,0,0,0,0,1,0,0,0,0
27,68607141,73509983,17600,17600,17600,5.32,530.03,88000.0,26.59,0,...,0,0,1,0,0,1,0,0,0,0
28,68476715,73366561,6000,6000,6000,7.49,186.61,100000.0,13.28,1,...,0,0,0,0,0,1,0,0,0,0
29,67715283,72569997,16000,16000,16000,12.88,538.18,65000.0,18.96,0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4970,68543519,73433250,8000,8000,8000,9.80,257.39,65000.0,19.70,0,...,0,0,0,0,0,1,0,0,0,0
4971,68413539,73303262,25000,25000,25000,17.27,894.69,88500.0,19.84,0,...,0,0,0,0,0,1,0,0,0,0
4972,68393586,73283316,20000,20000,20000,11.99,664.20,75000.0,20.80,1,...,0,0,0,0,0,1,0,0,0,0
4973,67820032,72678781,18000,18000,18000,11.99,597.78,45000.0,21.21,0,...,0,0,0,0,0,1,0,0,0,0
4974,68373625,73263353,25000,25000,25000,17.27,894.69,150000.0,11.57,0,...,0,0,1,0,0,1,0,0,0,0
4975,67840032,72698779,25000,25000,25000,19.48,922.48,50000.0,17.69,0,...,0,0,0,0,0,1,0,0,0,0
4976,68373615,73263342,4800,4800,4800,8.49,151.51,42000.0,14.71,0,...,0,0,0,0,0,1,0,0,0,0
4977,68483535,73373266,11000,11000,11000,13.99,375.91,57200.0,15.04,0,...,0,0,0,0,0,1,0,0,0,0
4978,68593246,73482964,25000,25000,25000,17.27,894.69,50000.0,22.23,0,...,0,0,0,0,0,1,0,0,0,0
4979,68473507,73363230,12000,12000,12000,5.32,361.38,77000.0,18.06,0,...,0,0,0,0,0,1,0,0,0,0
4980,68503526,73393256,12000,12000,12000,12.88,272.31,75000.0,17.01,0,...,0,0,0,0,0,1,0,0,0,0
4981,68433413,73323139,23500,23500,23500,11.48,774.72,55000.0,14.73,0,...,0,0,0,0,0,1,0,0,0,0
4982,68393584,73283314,6000,6000,6000,11.99,199.26,60000.0,11.54,0,...,0,0,0,0,0,1,0,0,0,0
4983,67185272,71985986,26400,26400,26400,7.49,821.09,65000.0,23.97,0,...,0,0,0,0,0,1,0,0,0,0
4984,68603141,73505854,15000,15000,15000,5.32,451.73,200000.0,13.47,0,...,0,0,0,0,0,1,0,0,0,0
4985,68433505,73323237,21000,21000,20825,13.99,488.53,75000.0,5.01,0,...,0,0,0,0,0,1,0,0,0,0
4986,67257389,72059158,5000,5000,5000,11.99,166.05,37000.0,34.35,0,...,0,0,0,0,0,1,0,0,0,0
4987,68513342,73403060,25000,25000,25000,11.99,555.99,101000.0,10.61,0,...,0,0,0,0,0,1,0,0,0,0
4988,68182428,73050150,5150,5150,5150,15.77,180.48,20200.0,26.62,0,...,0,0,0,0,0,1,0,0,0,0
4989,68383489,73273212,4000,4000,4000,10.78,130.54,60000.0,13.35,0,...,0,0,0,1,0,1,0,0,0,0
4990,68393441,73283162,26500,26500,26500,12.88,891.36,53000.0,22.19,0,...,0,0,0,0,0,1,0,0,0,0
4991,68563457,73453179,9150,9150,9150,17.97,330.66,50000.0,1.44,0,...,0,0,0,0,0,1,0,0,0,0
4992,67635995,72489727,6000,6000,6000,22.45,230.55,25000.0,31.88,0,...,0,0,0,1,0,1,0,0,0,0
4993,68338238,73190014,12000,12000,12000,13.99,410.08,50000.0,20.98,0,...,0,0,0,0,0,1,0,0,0,0
4994,68493476,73383202,16000,16000,16000,10.78,346.13,40000.0,15.69,0,...,0,0,0,0,0,1,0,0,0,0
4995,68443401,73333133,24000,24000,23975,16.59,591.19,70000.0,10.68,1,...,0,0,0,0,0,1,0,0,0,0
4996,68403472,73293197,8000,8000,8000,13.99,273.39,117000.0,13.93,0,...,0,0,0,0,0,1,0,0,0,0
4997,66426007,71161868,18000,18000,17925,18.99,466.84,50000.0,14.41,0,...,0,0,0,0,0,1,0,0,0,0
4998,67635369,72489085,11400,11400,11400,13.44,261.96,44000.0,7.53,0,...,0,0,0,0,0,1,0,0,0,0
4999,68433410,73323134,4800,4800,4800,17.97,173.46,65000.0,35.01,0,...,0,0,0,0,0,1,0,0,0,0

### Dropping Dataframe Columns